Repository elainatesfai/BTM_WebPage, pull requests merged in 2022-09, with the labels that each got.

#8 Contact
  public/index.html
  src/components/Navbar.jsx
  src/components/PageIntro.jsx
  src/components/Services.jsx
  src/components/Team.jsx
  src/css/about.css
  src/css/contact.css
  src/css/experts.css
  src/css/footer.css
  src/css/pageIntro.css
  src/css/services.css
  src/css/subServices.css
  src/css/team.css
Labels: enhancement

#10 Alan Changes #2 from Meeting
  src/App.js
  src/components/Experts.jsx
  src/components/Navbar.jsx
  src/components/Recruitment.jsx
  src/components/Team.jsx
  src/components/commonStructure/SubServiceCard.jsx
  src/css/Recruitment.css
  src/css/services.css
  src/css/subServices.css
Labels: documentation, enhancement

#12 Marwan Changes
  public/favicon.ico
  public/index.html
  src/components/About.jsx
  src/components/Experts.jsx
  src/components/InfoCards.jsx
  src/components/Navbar.jsx
  src/components/PageIntro.jsx
  src/components/Recruitment.jsx
  src/components/Services.jsx
  src/components/SubServices.jsx
  src/components/Team.jsx
  src/css/Recruitment.css
  src/css/about.css
  src/css/experts.css
  src/css/infoCards.css
  src/css/navbar.css
  src/css/pageIntro.css
  src/css/services.css
  src/css/subServices.css
  src/css/team.css
  src/images/AI.png
  src/images/AI_image.png
  src/images/BTM-LOGO-IMG-Final.jpg
  src/images/Code Development _Outline.png
  src/images/Experts/Alaa_Marshan.png
  src/images/Experts/Alan_Serrano_Rico.png
  src/images/Experts/Alina_Miron.png
  src/images/Experts/David_Bell.png
  src/images/Experts/Derek_Groen.png
  src/images/Experts/Giuseppe_Destefanis.png
  src/images/Experts/Isabel_Sasoon.png
  src/images/Experts/Kate_Hone.png
  src/images/Experts/Mahir_Arzoky.png
  src/images/Experts/No_Picture.png
  src/images/Experts/Rumyana_Neykova.png
  src/images/Experts/Stephen_Swift.png
  src/images/Experts/Timothy_Cribbin.png
  src/images/Experts/header.png
  src/images/Experts/mandeepbanner.png
  src/images/Experts/phillipbanner.png
  src/images/Logo_btm.png
  src/images/Logo_btm1.png
  src/images/Motivation_Outline.png
  src/images/Navbar-icon.png
  src/images/School_Outline.png
  src/images/Talents/ElainaTesfai.png
  src/images/Talents/IslamRaihan.png
  src/images/Talents/MarwanHajMohamed.png
  src/images/Talents/ShrawaniMenghal.png
  src/images/Talents/ThoyburRohman.png
  src/images/Target_Outline.png
  src/images/Team presentation _Outline.png
  src/images/Team work_Two Color.png
  src/images/Team_Work.png
  src/images/brunel-profile.png
  src/images/img1.jpeg
Labels: documentation, duplicate

#13 New Talents Added
  package.json
  src/components/Contact.jsx
  src/components/Experts.jsx
  src/components/Footer.jsx
  src/components/Team.jsx
  src/css/contact.css
  src/images/Experts/Alan_Serrano_Rico.png
  src/images/Talents/RituGulia.png
  src/images/Talents/SamuelAsareBotwe.png
Labels: documentation, enhancement

#14 Small Iterations
  src/components/Team.jsx
  src/components/commonStructure/ExpertsCard.jsx
  src/components/commonStructure/TalentCard.jsx
  src/css/infoCards.css
  src/css/navbar.css
Labels: documentation, enhancement

#16 More of Alan Changes
  public/index.html
  src/components/Contact.jsx
  src/components/Footer.jsx
  src/components/Recruitment.jsx
  src/components/Team.jsx
  src/css/Recruitment.css
  src/css/about.css
  src/css/contact.css
  src/css/footer.css
  src/css/infoCards.css
  src/images/Talents/KiranVelpula.png
Labels: bug, documentation, enhancement
